input {
  file {
    # Aponta para o arquivo de log gerado pela API FastAPI
    path => "${PWD}/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null" # Garante que ele releia o arquivo sempre que testarmos
  }
}

filter {
  # Grok para quebrar o formato: 2026-06-21 13:18:10,123 - INFO - Mensagem do log
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:log_timestamp} - %{LOGLEVEL:log_level} - %{GREEDYDATA:log_message}" }
  }

  date {
    match => [ "log_timestamp", "yyyy-MM-dd HH:mm:ss,SSS" ]
    target => "@timestamp"
  }
}

output {
  # Exibe o resultado estruturado no terminal
  stdout { 
    codec => rubydebug 
  }
}
