name: Python Application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Atualizado de @v3 para @v4
    - name: Checkout de codigo
      uses: actions/checkout@v4

    # Atualizado de @v4 para @v5
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Instalar Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    # Atualizado de @v3 para @v4
    - name: Configurar Cache do Poetry
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Instalar dependencias do projeto
      run: poetry install --no-root --no-interaction

    - name: Rodar testes com pytest
      run: poetry run pytest